server:
  port: 9001


spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes[2]:
        id: task-service
        uri: lb://task-service
        predicates[0]: Path=/tasks/**
      routes[0]:
        id: keycloak-client
        uri: lb://keycloak-client
        predicates[0]: Path=/users/**
      routes[1]:
        id: gateway-service
        uri: lb://gateway-service
        predicates[0]: Path=/gateway/**

    consul:
      host: 192.168.99.100
      config:
        enabled: false
      port: 8500

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ream-mini-project
          jwk-set-uri: http://localhost:8080/auth/realms/ream-mini-project/protocol/openid-connect/certs
#server:
#  ssl:
#    key-store-password: test123
#    key-store: classpath:ssldemo.p12
#    key-store-type: PKCS12
#    key-alias: ssldemo
#    enabled: 'true'
springdoc:
  swagger-ui:
    urls[2]:
      name: Task Service APIs
      url: /task-service/v3/api-docs
    urls[0]:
      url: /keycloak-client/v3/api-docs
      name: Keycloak client APIs
    urls[1]:
      url: /gateway-service/v3/api-docs
      name: Gateway Service APIs




#springdoc:
#  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
#        primaryName: API Gateway Service
#      - url: /task-service/v3/api-docs
#        name: task Service
#        primaryName: Task Service
#      - url: /keycloak-client/v3/api-docs
#        name: Keycloak Client
#        primaryName: Keycloak Client

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true



